name = "ToeplitzCUDA_Eigen_Refinement"
uuid = "3d553849-0536-4eb2-b845-3191e399a7ed"
authors = ["David Meadon"]
version = "1.0.0-DEV"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
IterativeRefinement = "bcb6b82e-7479-5933-8c8e-2e0b909ee6a3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
